appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: g7QVi3YTVQs5oZayyleXtEI0qE3zaWAVozUfZ1InAWMnsZfWIBTp6x6Zj++ZEubQ9BzCk9UpLIS2G/JxuUbZtDW+Usjxzd+eaQt0Ywt/dgLF8gAMnWo6Fnht28EfOFatxAvAGGFF2OeDwHD0oFloKCiB9itbX0E3Kxr7HnP+RfnIOy6l+e4TJt22Bnwf+IrLttk/w13A9buZWGd2farCgAGYwUkyu5f9cx3t66HR9NES87J05oTRiWyqmRTeGRP9uBhWO04FEagn2AGWomqshofjuhoIOLhctGYusvDcjJO2H+r/ArbY2yW7m0Sq3HojHzHENVQClmdHO3fNAUMkyC3ISCaUa1TbqEYYfGIBtt0+9zjG9Zu5I6EVoNfd7t8JxN6Bfv3URnlSEneWx+fQmlFu33rIuT/j0EnKRmAYldAaTVZpQ/tmTsEIV6n4PwQwf1kKgiSkORYJQKXfU2lg46wpLxe39gf3chuOumkU0e0KMP5p0oVrWjB3NB/QQht8ntR+mT7BBWCKLMVFhXeYAG3lppbQx08csmNziqbWqT9CipEc7zXgo+tw02e24l0VpxRGz5yVM/ZTEsAFuTopIrDYspQtL80cAYHlCqmG1A2xB5pI18jMWNxWMTS0lcSsJxA/SFQb2mSeyrZqO11stuxtpW7JRE+7GLqrfm+j/XY=
conda_forge_output_validation: true
