travis:
  secure:
    BINSTAR_TOKEN: n3/WHNtwAKYhLrLy6J4AH/DeHYU5ahlMc41JECU0nu/vXC/f1vgcjT8F19HQRVUfLY/Uxia2VZVm73oZxKct902FsG5wQiXjo3nJiGchO8gumK1sL84eHUK4efaRP8YCmxl/ilfOFZFFu1DzRB7tPtT9WnzqIX0CIFjusdZYmTPSk9bQuZMTFLo1wQDPcPQhToEhz10GVH39XzkquuaAfQweKumDg/Hzv/NUGMiBR9qmfCtEAXp5maiwMFQUuKLJpdwxY07mQzMxXyEbuSJcdqDys8aRDEcn8qaakLC62+c0ZMg4lSYb9SfKqIhn7PbLbLPaXsrapjTmV4caSZhVmY3uvHEnhBKdO1N6/RBA8wGt/vd+F0bDcmu4nZCeNoBQAYJDB2ISeXH3pznuzN/OCwCgbDOgac7m2Z1uuaKMOndwky7DLFubC8SVxY0tF0kxVB9bPdelDUIRf8yIDbYzwyzxx8dhsxWdqmHwlyRRtE3n3Gi2YhuLVcZzcnmQBATk4oHhdn/D9D0JmshvAjEq+13eJn7AqPejnL4pLNs0mN385CVcZEOAML/1VCggwQExz8nxwJb2uMGkxZGmyFA25+gUXUlCP7C+BDOFGOoR9WvoW1BkyRu9F7z0Y0o5c1ipr5W7Q4rqYgFZTj7B5YWp2jvRK5Ya8mhIE4jD+x2Ta4A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
